### ISSUE TITLE
CLI Templates

### ISSUE THREAD

**Issue by git001** [openshift-evangelists/openshift-cookbook#10] opened 2018-09-18 09:27 UTC
#### What is the new topic you would like to added to the OpenShift cookbook?

This topic should handle several `oc get -o ... ` snippets.

#### If this is to help you solve a specific problem, can you describe that problem?

The problem is that the output of `oc get -o wide|name` is not very easy to handle in further processes/pipes. Because of that a snippet collection with some suggestion how to handle jsonpath or golang text template would be very helpful.

**Comment by GrahamDumpleton** [comment] 2018-10-30 02:55
Duplicate of https://github.com/openshift-evangelists/openshift-cookbook/issues/3

**Closed by GrahamDumpleton** 2018-10-30 02:55 UTC
